# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BeyondTheClouds Blog
email: discovery-contact@inria.fr
description: "The <a href='https://beyondtheclouds.github.io/'>Discovery</a> Initiative.
  Discover what could happen beyond the Clouds!"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://beyondtheclouds.github.io/blog/" # the base hostname & protocol for your site
twitter_username: BeyondClouds_io
repository: "BeyondTheClouds/blog"
#github_username:

# Build settings
markdown: kramdown
highlighter: rouge
